on: [push, pull_request]
name: test
jobs:
  upgrade:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['ojs','omp','ops']
        database: [ 'pgsql','mysql','mariadb']
        php-version: [ '8.1' ,'8.2']
      
    name: test
    steps:
      - uses: withanage/test-action@v1
        with:
          application:  ${{matrix.application}}
          repository: 'pkp'
          branch: 'main' 
  